### ISSUE TITLE
Interesting projects

### ISSUE THREAD

**Issue by louis-kento** [IndigoFloyd/Strawberry#1]
Judging fruit ripeness based on peel color is indeed a great project, but I have been to strawberry picking gardens where there are some new varieties with white fruits that are ripe, and if in the past I think this project did have a great deal of promise, but in the era of BioBreeding 4.0 predicting based on peel color is not necessarily enough. I have an idea to do some work starting from the naked seeds of strawberry fruits, and I am looking forward to your comments and ideas.

**Comment by IndigoFloyd** [comment]
Thanks a lot for your warm review. There are indeed multiple kinds of strawberries, and what this project does is not useful enough to solve this problem. I'm not an expert in this category, and the dataset of this project comes from a public dataset. So I think maybe this project is all I can do now. But I'm still very interested in what you mentioned, would you please tell me more about how can I start from the naked seeds of strawberry fruits?

**Comment by louis-kento** [comment]
Your project seems to take part in  an agricultural competition organized by BGI in 2023, I think it is a bit difficult to segment strawberry seeds from the available photos, but so far it looks like the seeds on the outside of the strawberry are in a process of roughly changing from green to black during the ripening process. Because segmenting all the seeds is a big job, and also some areas of the seeds may not provide classification model accuracy due to light or contact stress but rather increase the workload. In a word .

I suggest you find specific areas of seeds on the outside of the strawberry to represent ripening.

**Comment by IndigoFloyd** [comment]
Well, not really. I did this project just for a skill test assigned by my Master's degree intended professor 😂. But thanks again for your suggestions, maybe we could exchange our contact information like WeChat for future conversation 🥹.

**Comment by louis-kento** [comment]
准硕士就做了这个项目挺厉害的，我是兰大在读硕士菜鸟一个，你可以通过这个号码联系到我：13253779912







-----原始邮件-----
发件人:IndigoFloyd ***@***.***>
发送时间:2024-05-23 17:34:13 (星期四)
收件人: IndigoFloyd/Strawberry ***@***.***>
抄送: louis-kento ***@***.***>, Author ***@***.***>
主题: Re: [IndigoFloyd/Strawberry] Interesting projects (Issue #1)






Well, not really. I did this project just for a skill test assigned by my Master's degree intended professor 😂. But thanks again for your suggestions, maybe we could exchange our contact information like WeChat for future conversation 🥹.
